name: DevSecOps Pipeline

on: [pull_request]

jobs:
  git-secrets:
    uses: ./.github/workflows/secrets.yml
  snyk:
    needs: [git-secrets]
    uses: ./.github/workflows/snyk.yml
    secrets: inherit
