name: DevSecOps Pipeline

on: [pull_request, push]

jobs:
  # git-secrets:
  #   uses: ./.github/workflows/secrets.yml
  snyk:
    # needs: [git-secrets]
    uses: ./.github/workflows/snyk.yml
    secrets: inherit
  deploy:
    # needs: [snyk]
    uses: ./.github/workflows/deploy-k8s.yml
    secrets: inherit