name: Git Secrets

on: [workflow_call]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          repository: awslabs/git-secrets

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install git secret
        run: sudo make install

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: develop

      - name: Scan the secrets with Talisman
        uses: carhartl/talisman-secrets-scan-action@v1.4.0

      - name: Run git-secrets
        run: |
          git secrets --install
          git secrets --register-aws
          git secrets --scan --recursive
