
name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: develop

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: awslabs/git-secrets
        path: ./git-secrets/

    - name: Check directory
      run: ls -al

