
name: Git Secrets

on: [workflow_call]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        repository: awslabs/git-secrets

    - name: Use Node.js 
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install snyk
      run: |
        npm install -g snyk
